name: Windows Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Install dependencies (Optional)
        run: |
          git pull origin
          npm install 
          